
- menu_name: "Services"#

- name: "About Us"
  url: "/info/"
  title: "About Us"#

- name: "Contact"
  url: "/contact/"
  title: "Contact"#
  #"Contact"#
# <a href="mailto:{{ site.contact }}">{{ site.contact }}</a>

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
