
- menu_name: "Services"#

- name: "About JWA Classic"
  url: "/info/"
  title: "About Us"#

- name: "Contact"
  url: "/contact/"
  title: "Contact"#

- name: "Instagram"
  url: "https://www.instagram.com/djowinter/"
  title: "Instagram"#


- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
