
- menu_name: "About"#

- name: "JWA Classic"
  url: "/info/"
  title: "About Us"#

- name: "Instagram"
  url: "https://www.instagram.com/djowinter/"
  title: "Instagram"#

- name: "Facebook"
  url: "https://www.facebook.com/JWAClassic/"
  title: "Facebook"#

- name: "Youtube"
  url: "https://www.youtube.com/channel/UCaVQagkO5yhqmBjz7kdXQ8g/"
  title: "Youtube"#
